# Generated by Django 4.1.5 on 2023-02-01 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.CharField(max_length=280)),
                ("level", models.IntegerField()),
                ("casting_time", models.CharField(max_length=128)),
                ("duration", models.CharField(max_length=128)),
                ("school", models.CharField(max_length=128)),
                ("spell_range", models.CharField(max_length=128)),
                ("components", models.TextField()),
                ("description", models.TextField()),
                ("at_higher_levels", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SpellSlotProgression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spell_level", models.IntegerField()),
                ("slots_at_level", models.IntegerField()),
                (
                    "class_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.classtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpellSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("slots_remaining", models.IntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpellClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.classtype",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spells.spell"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="spell",
            name="classes",
            field=models.ManyToManyField(
                through="spells.SpellClass", to="characters.classtype"
            ),
        ),
        migrations.CreateModel(
            name="CharacterSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prepared", models.BooleanField()),
                ("costs_slot", models.BooleanField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spells.spell"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CastSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spells.spell"
                    ),
                ),
            ],
        ),
    ]
