# Generated by Django 4.1.5 on 2023-05-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_alter_character_user"),
        ("spells", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spellslotprogression",
            old_name="slots_at_level",
            new_name="slots",
        ),
        migrations.AddField(
            model_name="spellslotprogression",
            name="char_level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="characterspell",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spells",
                to="characters.character",
            ),
        ),
    ]
