# Generated by Django 4.1.5 on 2023-01-10 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedapp", "0002_post_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backstory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("title", models.CharField(max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CastSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=280)),
                ("level", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hidden", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedapp.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prepared", models.BooleanField()),
                ("costs_slot", models.BooleanField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedapp.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=280)),
                ("url", models.CharField(max_length=280)),
                ("has_spells", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=280)),
                ("url", models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("level", models.IntegerField()),
                ("casting_time", models.CharField(max_length=128)),
                ("duration", models.CharField(max_length=128)),
                ("school", models.CharField(max_length=128)),
                ("spell_range", models.CharField(max_length=128)),
                ("components", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SpellClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedapp.classtype",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="feedapp.spell"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpellSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("slots_remaining", models.IntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedapp.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpellSlotProgression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spell_level", models.IntegerField()),
                ("slots_at_level", models.IntegerField()),
                (
                    "class_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedapp.characterclass",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="report",
            name="post",
        ),
        migrations.RemoveField(
            model_name="report",
            name="reported_by",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
        migrations.AddField(
            model_name="spell",
            name="classes",
            field=models.ManyToManyField(
                through="feedapp.SpellClass", to="feedapp.classtype"
            ),
        ),
        migrations.AddField(
            model_name="characterspell",
            name="spell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feedapp.spell"
            ),
        ),
        migrations.AddField(
            model_name="characterclass",
            name="class_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feedapp.classtype"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="class_type",
            field=models.ManyToManyField(
                through="feedapp.CharacterClass", to="feedapp.classtype"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feedapp.race"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="castspell",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feedapp.character"
            ),
        ),
        migrations.AddField(
            model_name="castspell",
            name="spell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feedapp.spell"
            ),
        ),
        migrations.AddField(
            model_name="backstory",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feedapp.character"
            ),
        ),
    ]
