# Generated by Django 4.1.5 on 2023-01-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedapp", "0003_backstory_castspell_character_characterclass_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spellslotprogression",
            name="class_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feedapp.classtype"
            ),
        ),
    ]
