# Generated by Django 4.1.5 on 2023-01-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedapp", "0006_remove_spell_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="class_type",
        ),
        migrations.DeleteModel(
            name="CharacterClass",
        ),
    ]
