# Generated by Django 4.1.5 on 2023-01-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedapp", "0007_remove_character_class_type_delete_characterclass"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="class_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedapp.classtype",
            ),
            preserve_default=False,
        ),
    ]
