# Generated by Django 4.1.5 on 2023-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedapp", "0008_character_class_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="at_higher_levels",
            field=models.TextField(default="yes"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spell",
            name="description",
            field=models.TextField(default="yes"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spell",
            name="level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
